name: Create Repo Secrets

on:
  workflow_dispatch:

jobs:
  secrets:
    name: Create Repo Secrets
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: pwsh

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Required Repo Secrets
      shell: pwsh
      working-directory: Assets/Scripts      
      env:
        GH_TOKEN: ${{ secrets.TF_BACKEND }}
      run: |
        ./create-repo-secrets.ps1
